# 赞助配置

# GitHub赞助
# github: xiaozhe2018

# 其他赞助方式
# patreon: your_patreon
# open_collective: your_opencollective
# ko_fi: your_kofi
# custom: ['https://paypal.me/yourpaypal', 'https://www.buymeacoffee.com/yourname']

