# 生产环境配置
app:
  name: "GinForge Framework"
  version: "0.1.0"
  env: "production"
  debug: false
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# 服务端口配置
services:
  user_api:
    port: 8081
  merchant_api:
    port: 8082
  admin_api:
    port: 8083
  gateway:
    port: 8080
  gateway_worker:
    port: 8084
  demo:
    port: 8085

log:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/var/log/ginforge/app.log"
  max_size: 500
  max_age: 30
  max_backups: 10
  compress: true

database:
  driver: "mysql"
  host: "mysql-server"
  port: 3306
  database: "ginforge_prod"
  username: "ginforge_user"
  password: "${DB_PASSWORD}"
  charset: "utf8mb4"
  timezone: "Asia/Shanghai"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: "2h"
  log_level: "warn"

redis:
  enabled: true
  host: "redis-server"
  port: 6379
  password: "${REDIS_PASSWORD}"
  database: 0
  pool_size: 20
  min_idle_conns: 10
  max_retries: 3
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_timeout: "5m"
  idle_check_frequency: "1m"

cache:
  default_ttl: "30m"
  max_size: 10000
  cleanup_interval: "1h"

jwt:
  secret: "${JWT_SECRET}"
  expire: "24h"
  issuer: "GinForge"
  audience: "GinForge-Users"

rate_limit:
  enabled: true
  rps: 1000
  burst: 2000
  window: "1m"

cors:
  enabled: true
  origins: ["https://yourdomain.com", "https://api.yourdomain.com"]
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  headers: ["Content-Type", "Authorization", "X-Requested-With"]
  credentials: true
  max_age: "12h"

monitor:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/healthz"
  ready_path: "/readyz"

# 服务发现配置
service_discovery:
  type: "consul"
  consul:
    address: "consul-server:8500"
    datacenter: "dc1"
    service_name: "ginforge"
    service_id: "ginforge-1"
    service_tags: ["api", "v1"]
  etcd:
    endpoints: ["etcd-server:2379"]
    timeout: "5s"
    ttl: "30s"

# 微服务配置
microservices:
  user_api:
    name: "user-api"
    port: 8081
    health_path: "/healthz"
    metrics_path: "/metrics"
  merchant_api:
    name: "merchant-api"
    port: 8082
    health_path: "/healthz"
    metrics_path: "/metrics"
  admin_api:
    name: "admin-api"
    port: 8083
    health_path: "/healthz"
    metrics_path: "/metrics"
  gateway:
    name: "gateway"
    port: 8080
    health_path: "/healthz"
    metrics_path: "/metrics"
  gateway_worker:
    name: "gateway-worker"
    port: 8084
    health_path: "/healthz"
    metrics_path: "/metrics"
  demo:
    name: "demo"
    port: 8085
    health_path: "/healthz"
    metrics_path: "/metrics"

# 外部服务配置
external_services:
  user_api_url: "http://user-api:8081"
  merchant_api_url: "http://merchant-api:8082"
  admin_api_url: "http://admin-api:8083"

# 文件上传配置
upload:
  max_size: 50
  allowed_types: ["image/jpeg", "image/png", "image/gif", "application/pdf"]
  upload_path: "/var/uploads"
  temp_path: "/var/temp"

# 邮件配置
email:
  enabled: true
  smtp_host: "smtp.yourdomain.com"
  smtp_port: 587
  smtp_username: "${SMTP_USERNAME}"
  smtp_password: "${SMTP_PASSWORD}"
  from_name: "GinForge"
  from_email: "noreply@yourdomain.com"

# 短信配置
sms:
  enabled: true
  provider: "aliyun"
  access_key: "${SMS_ACCESS_KEY}"
  secret_key: "${SMS_SECRET_KEY}"
  sign_name: "GinForge"
  template_code: "SMS_123456789"

# 安全配置
security:
  bcrypt_cost: 12
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  password_min_length: 8
  password_require_uppercase: true
  password_require_lowercase: true
  password_require_numbers: true
  password_require_symbols: true
